import { FlatList, StyleSheet } from "react-native";
import styled from "styled-components/native";
import { ChatItem, ChatItemProps } from "./ChatItem";
import { SearchEntry } from "./SearchEntry";
import { useApp } from "@/hooks";

const Container = styled.View`
  flex: 1;
`;

const MOCK_DATA = [
  {
    username: "Zorro",
    publicKey: "key-v1-01",
    avatarSeed: "seed_8291",
    address: "0x71C...a4b",
    lastMsg: "你刚才发的那个代码运行了吗？",
    time: "18:20",
  },
  {
    username: "Satoshi",
    publicKey: "key-v1-02",
    avatarSeed: "seed_1024",
    address: "0x1A2...c3d",
    lastMsg: "The Times 03/Jan/2009 Chancellor on brink of second bailout for banks.",
    time: "18:15",
  },
  {
    username: "Vitalik",
    publicKey: "key-v1-03",
    avatarSeed: "seed_5566",
    address: "0xAbC...eF0",
    lastMsg: "我们下周的以太坊开发者会议你参加吗？",
    time: "17:50",
  },
  {
    username: "Elon Musk",
    publicKey: "key-v1-04",
    avatarSeed: "seed_x_ae",
    address: "0xDed...b01",
    lastMsg: "To the moon! 🚀",
    time: "17:45",
  },
  {
    username: "Ace",
    publicKey: "key-v1-05",
    avatarSeed: "seed_fire",
    address: "0x998...f22",
    lastMsg: "在这个大海的尽头，一定有答案。",
    time: "17:30",
  },
  {
    username: "Luffy",
    publicKey: "key-v1-06",
    avatarSeed: "seed_meat",
    address: "0x555...a11",
    lastMsg: "肉！我要吃肉！🍖",
    time: "16:20",
  },
  {
    username: "Nami",
    publicKey: "key-v1-07",
    avatarSeed: "seed_gold",
    address: "0x888...777",
    lastMsg: "这次航行的贝里已经结算清楚了。",
    time: "16:15",
  },
  {
    username: "Zoro",
    publicKey: "key-v1-08",
    avatarSeed: "seed_sword",
    address: "0x111...222",
    lastMsg: "我又迷路了，你在哪？",
    time: "15:40",
  },
  {
    username: "Sanji",
    publicKey: "key-v1-09",
    avatarSeed: "seed_cook",
    address: "0x333...444",
    lastMsg: "今天的女士午餐准备好了。☕",
    time: "15:10",
  },
  {
    username: "Robin",
    publicKey: "key-v1-10",
    avatarSeed: "seed_book",
    address: "0x666...999",
    lastMsg: "历史的真相总是藏在石碑之后。",
    time: "14:55",
  },
  {
    username: "Chopper",
    publicKey: "key-v1-11",
    avatarSeed: "seed_candy",
    address: "0x000...111",
    lastMsg: "就算你夸我我也不会高兴的，混蛋～",
    time: "14:20",
  },
  {
    username: "Franky",
    publicKey: "key-v1-12",
    avatarSeed: "seed_super",
    address: "0x222...333",
    lastMsg: "SUUUUPER!!! 🤖",
    time: "14:05",
  },
  {
    username: "Brook",
    publicKey: "key-v1-13",
    avatarSeed: "seed_soul",
    address: "0x444...555",
    lastMsg: "虽然我已经没有眼睛了，但我看得很清楚。哟呵呵呵～",
    time: "13:40",
  },
  {
    username: "Jinbe",
    publicKey: "key-v1-14",
    avatarSeed: "seed_fish",
    address: "0x777...888",
    lastMsg: "仁义礼智，吾辈之本。",
    time: "13:20",
  },
  {
    username: "Steve Jobs",
    publicKey: "key-v1-15",
    avatarSeed: "seed_apple",
    address: "0x999...000",
    lastMsg: "Stay hungry, stay foolish.",
    time: "12:55",
  },
  {
    username: "Bill Gates",
    publicKey: "key-v1-16",
    avatarSeed: "seed_ms",
    address: "0xAAA...BBB",
    lastMsg: "你对最近的 AI 发展怎么看？",
    time: "12:30",
  },
  {
    username: "Sam Altman",
    publicKey: "key-v1-17",
    avatarSeed: "seed_openai",
    address: "0xCCC...DDD",
    lastMsg: "AGI is coming sooner than we think.",
    time: "12:10",
  },
  {
    username: "Linus Torvalds",
    publicKey: "key-v1-18",
    avatarSeed: "seed_linux",
    address: "0xEEE...FFF",
    lastMsg: "Talk is cheap, show me the code.",
    time: "11:50",
  },
  {
    username: "Jeff Bezos",
    publicKey: "key-v1-19",
    avatarSeed: "seed_amazon",
    address: "0x123...456",
    lastMsg: "It's always Day 1.",
    time: "11:30",
  },
  {
    username: "Mark Zuckerberg",
    publicKey: "key-v1-20",
    avatarSeed: "seed_meta",
    address: "0x789...012",
    lastMsg: "我们要把整个社交网络搬进元宇宙。",
    time: "11:05",
  },
  {
    username: "Jack Ma",
    publicKey: "key-v1-21",
    avatarSeed: "seed_alibaba",
    address: "0x345...678",
    lastMsg: "我对钱没有兴趣。",
    time: "10:45",
  },
  {
    username: "Pony Ma",
    publicKey: "key-v1-22",
    avatarSeed: "seed_tencent",
    address: "0x901...234",
    lastMsg: "这个新版本的微信你觉得怎么样？",
    time: "10:20",
  },
  {
    username: "Zhang Yiming",
    publicKey: "key-v1-23",
    avatarSeed: "seed_tiktok",
    address: "0x567...890",
    lastMsg: "始终创业，保持延迟满足。",
    time: "10:05",
  },
  {
    username: "Rick",
    publicKey: "key-v1-24",
    avatarSeed: "seed_c137",
    address: "0xABC...137",
    lastMsg: "Wubba Lubba Dub Dub!",
    time: "09:40",
  },
  {
    username: "Morty",
    publicKey: "key-v1-25",
    avatarSeed: "seed_morty",
    address: "0xDEF...456",
    lastMsg: "Oh geez, Rick, I don't know about this...",
    time: "09:35",
  },
  {
    username: "Batman",
    publicKey: "key-v1-26",
    avatarSeed: "seed_gotham",
    address: "0x000...bat",
    lastMsg: "I am vengeance. I am the night.",
    time: "03:00",
  },
  {
    username: "Joker",
    publicKey: "key-v1-27",
    avatarSeed: "seed_ha",
    address: "0x666...lol",
    lastMsg: "Why so serious? HA HA HA!",
    time: "02:55",
  },
  {
    username: "Spider-Man",
    publicKey: "key-v1-28",
    avatarSeed: "seed_nyc",
    address: "0xweb...001",
    lastMsg: "Your friendly neighborhood Spider-Man.",
    time: "昨日",
  },
  {
    username: "Iron Man",
    publicKey: "key-v1-29",
    avatarSeed: "seed_stark",
    address: "0x300...love",
    lastMsg: "I love you three thousand.",
    time: "昨日",
  },
  {
    username: "Captain America",
    publicKey: "key-v1-30",
    avatarSeed: "seed_shield",
    address: "0xusa...001",
    lastMsg: "I can do this all day.",
    time: "昨日",
  },
  {
    username: "Thanos",
    publicKey: "key-v1-31",
    avatarSeed: "seed_snap",
    address: "0x50p...cent",
    lastMsg: "I am inevitable.",
    time: "昨日",
  },
  {
    username: "Dumbledore",
    publicKey: "key-v1-32",
    avatarSeed: "seed_hp",
    address: "0xmag...ic1",
    lastMsg: "决定我们成为什么样人的，是我们的选择。",
    time: "昨日",
  },
  {
    username: "Voldemort",
    publicKey: "key-v1-33",
    avatarSeed: "seed_dark",
    address: "0xnos...e00",
    lastMsg: "Avada Kedavra!",
    time: "昨日",
  },
  {
    username: "Neo",
    publicKey: "key-v1-34",
    avatarSeed: "seed_matrix",
    address: "0x010...101",
    lastMsg: "Knock, knock, Neo.",
    time: "2月15日",
  },
  {
    username: "Morpheus",
    publicKey: "key-v1-35",
    avatarSeed: "seed_pill",
    address: "0xred...blu",
    lastMsg: "你选择红药丸还是蓝药丸？",
    time: "2月15日",
  },
  {
    username: "Master Chief",
    publicKey: "key-v1-36",
    avatarSeed: "seed_halo",
    address: "0x117...000",
    lastMsg: "Wake me when you need me.",
    time: "2月14日",
  },
  {
    username: "Kratos",
    publicKey: "key-v1-37",
    avatarSeed: "seed_god",
    address: "0xwar...001",
    lastMsg: "BOY!",
    time: "2月14日",
  },
  {
    username: "Ellie",
    publicKey: "key-v1-38",
    avatarSeed: "seed_last",
    address: "0x911...lou",
    lastMsg: "Endure and survive.",
    time: "2月13日",
  },
  {
    username: "Geralt",
    publicKey: "key-v1-39",
    avatarSeed: "seed_witcher",
    address: "0xtea...m_y",
    lastMsg: "来局昆特牌吗？",
    time: "2月12日",
  },
  {
    username: "Ciri",
    publicKey: "key-v1-40",
    avatarSeed: "seed_space",
    address: "0xtime...001",
    lastMsg: "我穿越了无数个世界才找到你。",
    time: "2月11日",
  },
  {
    username: "Solid Snake",
    publicKey: "key-v1-41",
    avatarSeed: "seed_metal_gear",
    address: "0xbox...001",
    lastMsg: "Keep you waiting, huh?",
    time: "2月10日",
  },
  {
    username: "Gordon Freeman",
    publicKey: "key-v1-42",
    avatarSeed: "seed_lambda",
    address: "0xhl3...nev",
    lastMsg: "...",
    time: "2月09日",
  },
  {
    username: "Mario",
    publicKey: "key-v1-43",
    avatarSeed: "seed_mario",
    address: "0xit_...me1",
    lastMsg: "It's-a me, Mario!",
    time: "2月08日",
  },
  {
    username: "Link",
    publicKey: "key-v1-44",
    avatarSeed: "seed_zelda",
    address: "0xhya...001",
    lastMsg: "Hyaaaa! Tsk! Hah!",
    time: "2月07日",
  },
  {
    username: "Cloud Strife",
    publicKey: "key-v1-45",
    avatarSeed: "seed_ff7",
    address: "0xfff...007",
    lastMsg: "Not interested.",
    time: "2月06日",
  },
  {
    username: "Sephiroth",
    publicKey: "key-v1-46",
    avatarSeed: "seed_one_wing",
    address: "0xbad...boy",
    lastMsg: "I will never be a memory.",
    time: "2月05日",
  },
  {
    username: "Darth Vader",
    publicKey: "key-v1-47",
    avatarSeed: "seed_sith",
    address: "0xdar...k_s",
    lastMsg: "I am your father.",
    time: "2月04日",
  },
  {
    username: "Yoda",
    publicKey: "key-v1-48",
    avatarSeed: "seed_jedi",
    address: "0xfor...ce1",
    lastMsg: "Do or do not. There is no try.",
    time: "2月03日",
  },
  {
    username: "Sherlock",
    publicKey: "key-v1-49",
    avatarSeed: "seed_221b",
    address: "0xdet...ect",
    lastMsg: "排除掉所有不可能，剩下的无论多么离奇，都是真相。",
    time: "2月02日",
  },
  {
    username: "Watson",
    publicKey: "key-v1-50",
    avatarSeed: "seed_doctor",
    address: "0xhel...p50",
    lastMsg: "Sherlock, 你又在折腾什么实验？",
    time: "2月01日",
  },
];
export function ChatList() {
  const { navigation, ROUTES } = useApp();
  const handlePressItem = (item: ChatItemProps) => () => {
    navigation.navigate(ROUTES.Chat, { avatarSeed: item.avatarSeed, username: item.username });
  };
  return (
    <Container>
      <FlatList
        data={MOCK_DATA}
        ListHeaderComponent={SearchEntry}
        renderItem={({ item }) => <ChatItem {...item} onPress={handlePressItem(item)} />}
        keyExtractor={item => item.publicKey}
        contentContainerStyle={styles.listContentContainer}
        showsVerticalScrollIndicator={false}
        removeClippedSubviews={true}
        windowSize={5}
        initialNumToRender={10}
      />
    </Container>
  );
}

const styles = StyleSheet.create({
  listContentContainer: {
    flexGrow: 1,
    paddingBottom: 8,
  },
});
